# Generated by Django 5.1.6 on 2025-02-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='localtion',
            new_name='location',
        ),
    ]
